### PR TITLE
Support monster searching (issue #4)

### PR DESCRIPTION
**Pull request by PrincessMadMath**
Fixing the issue #4

### CODE REVIEW

**Comment by PrincessMadMath** [comment]
Dude the styling is awful!

**Comment by PrincessMadMath** [comment]
Yeah I know other me, I just want to check how to do a pull request

**Comment by PrincessMadMath** [comment]
Is seem that you also want to test the comment section (talking with yourself you weirdo!)

**Comment by kfedorov** [comment]
Are you crazy?!

**Comment by PrincessMadMath** [comment]
Well this is awkward...

**Pull request merged**
